In [1]:
from keras import Model
from keras.models import Sequential
from keras.layers import Dense, MaxPool2D, Dropout,MaxPool2D, Activation,BatchNormalization, InputLayer, Embedding, Flatten, Conv2D,concatenate, MaxPooling2D, Input, TimeDistributed
from keras.optimizers import SGD, Adam, RMSprop
import keras.utils
from keras import backend as k
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from keras.preprocessing import image
from keras.layers import Flatten, LSTM
import numpy as np

Using TensorFlow backend.


In [2]:
#main
input_x=np.random.rand(1000,64,64,3)

In [3]:
#mian
cnnmodel = Sequential()
cnnmodel.add(Conv2D(64, 5, data_format="channels_last", kernel_initializer="he_normal", 
                 input_shape=(64, 64, 3)))
#cnnmodel.add(BatchNormalization())
cnnmodel.add(Activation("relu"))

cnnmodel.add(Conv2D(64, 4))
#cnnmodel.add(BatchNormalization())
cnnmodel.add(Activation("relu"))
cnnmodel.add(MaxPool2D(pool_size=(2, 2), strides=2))
cnnmodel.add(Dropout(0.5))

cnnmodel.add(Conv2D(32, 3))
#cnnmodel.add(BatchNormalization())
cnnmodel.add(Activation("relu"))

cnnmodel.add(Conv2D(32, 3))
#cnnmodel.add(BatchNormalization())
cnnmodel.add(Activation("relu"))

cnnmodel.add(MaxPool2D(pool_size=(2, 2), strides=2))
cnnmodel.add(Dropout(0.5))

cnnmodel.add(Flatten())
cnnmodel.add(Dense(512))
cnnmodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
cnnmodel.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 60, 60, 64)        4864      
_________________________________________________________________
activation_1 (Activation)    (None, 60, 60, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 57, 57, 64)        65600     
_________________________________________________________________
activation_2 (Activation)    (None, 57, 57, 64)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 28, 28, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 28, 28, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 26, 26, 32)        18464     
__________

In [14]:
#main
model = Sequential()                       
model.add(TimeDistributed(cnnmodel,input_shape=(1000,64,64,3)))

#mode1.add(LSTM(output_dim=128, return_sequences=True),(Input(shape=[1000,512])))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
time_distributed_9 (TimeDist (None, 1000, 512)         2457984   
Total params: 2,457,984
Trainable params: 2,457,984
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#cossnormality
apex_frame=cnn_output[-1]
coss_out = [cossim(apex_frame,x) for x in cnn_output]
Ff_frame = min_max_normalise(coss_out)

In [ ]:
def cossimilarity(f_vec):
    
    return 

In [ ]:
#weight regulizers
def weight_regulizer():
    
    return

In [ ]:
#bais regulizers
def bais_regulizer():
    
    return

In [9]:
model_1=Sequential();                          
model_1.add(TimeDistributed(cnnmodel,input_shape=(1000,64,64,3)))
mode1_1.add(LSTM(output_dim=(512),use_bias=True,bias_initializer='zeros', return_sequences=True, input_shape=(1000,512)))
#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_1.summary()

NameError: name 'mode1_1' is not defined

In [8]:
#discard
p1_model = Sequential()
inp_phase1 = Input(shape=(1000,512))
p1_lstm = LSTM(output_dim=(6), return_sequences=True)(inp_phase1)
phase1_out = Dense(6,activation='softmax')(p1_lstm)
p1_model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])
p1_model.summary()
# p2_lstm = LSTM(output_dim=(1000), return_sequences=True)(inp_phase2)
# phase2_out = Dense(1000)(p2_lstm)
# p2_model = Model(inputs= cnn_output, outputs=phase2_out)
# p2_model.compile(optimizer='adam', loss='mean_squared_error',metrics=['accuracy'])
# p2_model.summary()
#p1_model.compile(optimizer='ada,', loss='categorical_crossentropy',metrics=['accuracy'])

/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(return_sequences=True, units=6)`
  after removing the cwd from sys.path.


TypeError: Sequential model cannot be built: model is empty. Add some layers first.

In [89]:
#discard
model=Sequential();                          

model.add(TimeDistributed(Convolution2D(32, 3, 3, border_mode='same'), input_shape=(1000,64,64,1)))
model.add(TimeDistributed(Activation('relu')))
model.add(TimeDistributed(Convolution2D(32, 3, 3)))
model.add(TimeDistributed(Activation('relu')))
model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
model.add(TimeDistributed(Dropout(0.25)))
model.add(TimeDistributed(Flatten()))
model.add(TimeDistributed(Dense(512)))
#model.add(LSTM(20, return_sequences=True, name="lstm_layer_phase1"));      
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
time_distributed_135 (TimeDi (None, 1000, 64, 64, 32)  320       
_________________________________________________________________
time_distributed_136 (TimeDi (None, 1000, 64, 64, 32)  0         
_________________________________________________________________
time_distributed_137 (TimeDi (None, 1000, 62, 62, 32)  9248      
_________________________________________________________________
time_distributed_138 (TimeDi (None, 1000, 62, 62, 32)  0         
_________________________________________________________________
time_distributed_139 (TimeDi (None, 1000, 31, 31, 32)  0         
_________________________________________________________________
time_distributed_140 (TimeDi (None, 1000, 31, 31, 32)  0         
_________________________________________________________________
time_distributed_141 (TimeDi (None, 1000, 30752)       0         
__________

/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same")`
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3))`
  """


In [88]:
#discard
model = Sequential()
image_input = Input(shape=[1000, 64, 64, 3])
conv1 = TimeDistributed(Convolution2D(filters=32, kernel_size=(3, 3), strides=(1, 1),
                         padding='same', activation='relu', name='conv1'))(image_input)
pool1 = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(conv1)
conv_flatten = TimeDistributed(Flatten(name='conv_flatten'))(pool1)
conca_output = conv_flatten
dense1 = TimeDistributed(Dense(units=512, activation='relu', name='dense1'))(conca_output)
model = Model(inputs= image_input, outputs=dense1)
input1 = model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=1e-3))
inp = model.input
outputs = [layer.output for layer in model.layers]   
print(outputs)
model.summary()

[<tf.Tensor 'input_46:0' shape=(?, 1000, 64, 64, 3) dtype=float32>, <tf.Tensor 'time_distributed_131/Reshape_1:0' shape=(?, 1000, 64, 64, 32) dtype=float32>, <tf.Tensor 'time_distributed_132/Reshape_1:0' shape=(?, 1000, 32, 32, 32) dtype=float32>, <tf.Tensor 'time_distributed_133/Reshape_2:0' shape=(?, 1000, 32768) dtype=float32>, <tf.Tensor 'time_distributed_134/Reshape_1:0' shape=(?, 1000, 512) dtype=float32>]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_46 (InputLayer)        (None, 1000, 64, 64, 3)   0         
_________________________________________________________________
time_distributed_131 (TimeDi (None, 1000, 64, 64, 32)  896       
_________________________________________________________________
time_distributed_132 (TimeDi (None, 1000, 32, 32, 32)  0         
_________________________________________________________________
time_distributed_133 (TimeDi (None, 1000, 32768)       0

In [86]:
def E2Cons(weight_matrix):
    return 0
p1_model = Sequential()
p1_model.add(LSTM(output_dim=(512),use_bias=True,bias_initializer='zeros', return_sequences=True, input_shape=(1000,512)))
p1_model.add(Dense(6,activation='softmax'))
p1_model.compile(optimizer='adam', loss='mean_squared_error',metrics=['accuracy'])
# p1_model.
p1_model.summary()

/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(use_bias=True, bias_initializer="zeros", return_sequences=True, input_shape=(1000, 512..., units=512)`
  after removing the cwd from sys.path.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_21 (LSTM)               (None, 1000, 512)         2099200   
_________________________________________________________________
dense_28 (Dense)             (None, 1000, 6)           3078      
Total params: 2,102,278
Trainable params: 2,102,278
Non-trainable params: 0
_________________________________________________________________


In [76]:
x=[1,2,3,4,5]
y=[0,1,2,3,4,5,6]
y = keras.utils.to_categorical(y, num_classes=7)
print(y)

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]


In [ ]:
cnn_output = model.predict(seq)
cossnormality(cnn_output)
phase1_model.predict(cnn_output)   #recieved L1 final



In [3]:
import matplotlib.pyplot as plt
plt.ion()

In [4]:
(xtr,ytr),(xts,yts) = mnist.load_data()

In [5]:
K.backend.image_data_format()

'channels_last'

In [6]:
batch_size = 128
num_classes = 10
epochs=10
row,col = 28,28
if K.backend.image_data_format() == 'channels_first':
    xtr = xtr.reshape(xtr.shape[0], 1, row, col)
    xts = xts.reshape(xts.shape[0],1,row,col)
    inp_shape = (1,row,col)
else:
    xtr = xtr.reshape(xtr.shape[0], row,col,1)
    xts = xts.reshape(xts.shape[0], row,col,1)
    xts = xts.astype('float32')
    xtr = xtr.astype('float32')
    inp_shape = (row,col,1)
    
    

In [7]:
ytr = keras.utils.to_categorical(ytr,num_classes)
yts = keras.utils.to_categorical(yts,num_classes)

NameError: name 'keras' is not defined

In [8]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu', input_shape=inp_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
__________

In [60]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

In [61]:
model.fit(xtr, ytr,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(xts, yts))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 258s 4ms/step - loss: 1.9187 - acc: 0.8233 - val_loss: 0.0741 - val_acc: 0.9778
Epoch 2/10
60000/60000 [==============================] - 301s 5ms/step - loss: 0.1236 - acc: 0.9647 - val_loss: 0.0479 - val_acc: 0.9851
Epoch 3/10
60000/60000 [==============================] - 1766s 29ms/step - loss: 0.0902 - acc: 0.9747 - val_loss: 0.0432 - val_acc: 0.9859
Epoch 4/10
60000/60000 [==============================] - 290s 5ms/step - loss: 0.0725 - acc: 0.9793 - val_loss: 0.0449 - val_acc: 0.9850
Epoch 5/10
60000/60000 [==============================] - 266s 4ms/step - loss: 0.0610 - acc: 0.9824 - val_loss: 0.0413 - val_acc: 0.9881
Epoch 6/10
60000/60000 [==============================] - 281s 5ms/step - loss: 0.0532 - acc: 0.9847 - val_loss: 0.0395 - val_acc: 0.9867
Epoch 7/10
60000/60000 [==============================] - 269s 4ms/step - loss: 0.0465 - acc: 0.9864 - val_loss: 0.0334 

NameError: name 'x_test' is not defined

In [62]:
score = model.evaluate(xts, yts, verbose=0)
print( score)

[0.034145546473439752, 0.98899999999999999]


In [9]:
from keras.utils import plot_model
plot_model(model, to_file='model.png')

In [10]:
# Example of one output for whole sequence
from keras.models import Sequential
from keras.layers import LSTM
from numpy import array
# define model where LSTM is also output layer
model = Sequential()
model.add(LSTM(1, input_shape=(3,1)))
model.compile(optimizer='adam', loss='mse')
# input time steps
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

[[ 0.07451584]]


In [15]:
# Example of one output for each input time step
from keras.models import Sequential
from keras.layers import LSTM
from numpy import array
# define model where LSTM is also output layer
model = Sequential()
model.add(LSTM(1, return_sequences=True, input_shape=(3,1)))
model.compile(optimizer='adam', loss='mse')
# input time steps
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

[[[ 0.02108235]
  [ 0.06051913]
  [ 0.11521237]]]


In [ ]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1, return_state=True)(inputs1)
print(k.shape(lstm1[0]).eval(session=k.get_session()))
    #type(lstm1))
    #k.shape(lstm1).eval(session=k.get_session()))
model = Model(inputs=inputs1, outputs=lstm1)
model.compile(optimizer='adam', loss='mean_squared_error',metrics=['accuracy'])
model.summary()