In [102]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

# This does work by using only one sample:
data = [[0,0,0,1,2,3,4,5,6,7,8]]
data = np.array(data, dtype=float)
target = [1,2,3,4,5,6,7,8,9,10,11]
target = np.array(target, dtype=float)

data = data.reshape((1, 1, 11)) # Single batch, 1 time steps, 11 dimentions
target = target.reshape((-1, 11)) # Corresponds to shape (None, 11)

# Build Model
model = Sequential()  
model.add(LSTM(11, input_shape=(1, 11), unroll=False))
model.add(Dense(11))
model.compile(loss='mean_absolute_error', optimizer='adam')
model.fit(data, target, nb_epoch=1000, batch_size=1, verbose=2)

# Do the output values match the target values?

predict = model.predict(data)

/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/keras/models.py:944: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/1000
 - 3s - loss: 5.9519
Epoch 2/1000
 - 0s - loss: 5.9459
Epoch 3/1000
 - 0s - loss: 5.9398
Epoch 4/1000
 - 0s - loss: 5.9337
Epoch 5/1000
 - 0s - loss: 5.9274
Epoch 6/1000
 - 0s - loss: 5.9211
Epoch 7/1000
 - 0s - loss: 5.9148
Epoch 8/1000
 - 0s - loss: 5.9082
Epoch 9/1000
 - 0s - loss: 5.9014
Epoch 10/1000
 - 0s - loss: 5.8946
Epoch 11/1000
 - 0s - loss: 5.8876
Epoch 12/1000
 - 0s - loss: 5.8805
Epoch 13/1000
 - 0s - loss: 5.8733
Epoch 14/1000
 - 0s - loss: 5.8659
Epoch 15/1000
 - 0s - loss: 5.8586
Epoch 16/1000
 - 0s - loss: 5.8517
Epoch 17/1000
 - 0s - loss: 5.8446
Epoch 18/1000
 - 0s - loss: 5.8375
Epoch 19/1000
 - 0s - loss: 5.8302
Epoch 20/1000
 - 0s - loss: 5.8229
Epoch 21/1000
 - 0s - loss: 5.8154
Epoch 22/1000
 - 0s - loss: 5.8080
Epoch 23/1000
 - 0s - loss: 5.8007
Epoch 24/1000
 - 0s - loss: 5.7933
Epoch 25/1000
 - 0s - loss: 5.7858
Epoch 26/1000
 - 0s - loss: 5.7784
Epoch 27/1000
 - 0s - loss: 5.7709
Epoch 28/1000
 - 0s - loss: 5.7633
Epoch 29/1000
 - 0s - loss: 5

Epoch 232/1000
 - 0s - loss: 4.2858
Epoch 233/1000
 - 0s - loss: 4.2794
Epoch 234/1000
 - 0s - loss: 4.2729
Epoch 235/1000
 - 0s - loss: 4.2666
Epoch 236/1000
 - 0s - loss: 4.2603
Epoch 237/1000
 - 0s - loss: 4.2538
Epoch 238/1000
 - 0s - loss: 4.2474
Epoch 239/1000
 - 0s - loss: 4.2410
Epoch 240/1000
 - 0s - loss: 4.2346
Epoch 241/1000
 - 0s - loss: 4.2282
Epoch 242/1000
 - 0s - loss: 4.2219
Epoch 243/1000
 - 0s - loss: 4.2155
Epoch 244/1000
 - 0s - loss: 4.2092
Epoch 245/1000
 - 0s - loss: 4.2029
Epoch 246/1000
 - 0s - loss: 4.1965
Epoch 247/1000
 - 0s - loss: 4.1902
Epoch 248/1000
 - 0s - loss: 4.1838
Epoch 249/1000
 - 0s - loss: 4.1775
Epoch 250/1000
 - 0s - loss: 4.1711
Epoch 251/1000
 - 0s - loss: 4.1648
Epoch 252/1000
 - 0s - loss: 4.1584
Epoch 253/1000
 - 0s - loss: 4.1522
Epoch 254/1000
 - 0s - loss: 4.1459
Epoch 255/1000
 - 0s - loss: 4.1395
Epoch 256/1000
 - 0s - loss: 4.1331
Epoch 257/1000
 - 0s - loss: 4.1270
Epoch 258/1000
 - 0s - loss: 4.1207
Epoch 259/1000
 - 0s - loss:

Epoch 460/1000
 - 0s - loss: 3.0075
Epoch 461/1000
 - 0s - loss: 3.0022
Epoch 462/1000
 - 0s - loss: 2.9968
Epoch 463/1000
 - 0s - loss: 2.9913
Epoch 464/1000
 - 0s - loss: 2.9859
Epoch 465/1000
 - 0s - loss: 2.9803
Epoch 466/1000
 - 0s - loss: 2.9757
Epoch 467/1000
 - 0s - loss: 2.9714
Epoch 468/1000
 - 0s - loss: 2.9669
Epoch 469/1000
 - 0s - loss: 2.9624
Epoch 470/1000
 - 0s - loss: 2.9579
Epoch 471/1000
 - 0s - loss: 2.9531
Epoch 472/1000
 - 0s - loss: 2.9483
Epoch 473/1000
 - 0s - loss: 2.9435
Epoch 474/1000
 - 0s - loss: 2.9386
Epoch 475/1000
 - 0s - loss: 2.9336
Epoch 476/1000
 - 0s - loss: 2.9287
Epoch 477/1000
 - 0s - loss: 2.9237
Epoch 478/1000
 - 0s - loss: 2.9187
Epoch 479/1000
 - 0s - loss: 2.9137
Epoch 480/1000
 - 0s - loss: 2.9086
Epoch 481/1000
 - 0s - loss: 2.9036
Epoch 482/1000
 - 0s - loss: 2.8991
Epoch 483/1000
 - 0s - loss: 2.8945
Epoch 484/1000
 - 0s - loss: 2.8898
Epoch 485/1000
 - 0s - loss: 2.8851
Epoch 486/1000
 - 0s - loss: 2.8802
Epoch 487/1000
 - 0s - loss:

Epoch 688/1000
 - 0s - loss: 2.0358
Epoch 689/1000
 - 0s - loss: 2.0317
Epoch 690/1000
 - 0s - loss: 2.0274
Epoch 691/1000
 - 0s - loss: 2.0233
Epoch 692/1000
 - 0s - loss: 2.0193
Epoch 693/1000
 - 0s - loss: 2.0152
Epoch 694/1000
 - 0s - loss: 2.0110
Epoch 695/1000
 - 0s - loss: 2.0069
Epoch 696/1000
 - 0s - loss: 2.0027
Epoch 697/1000
 - 0s - loss: 1.9986
Epoch 698/1000
 - 0s - loss: 1.9944
Epoch 699/1000
 - 0s - loss: 1.9903
Epoch 700/1000
 - 0s - loss: 1.9861
Epoch 701/1000
 - 0s - loss: 1.9821
Epoch 702/1000
 - 0s - loss: 1.9781
Epoch 703/1000
 - 0s - loss: 1.9740
Epoch 704/1000
 - 0s - loss: 1.9699
Epoch 705/1000
 - 0s - loss: 1.9657
Epoch 706/1000
 - 0s - loss: 1.9615
Epoch 707/1000
 - 0s - loss: 1.9575
Epoch 708/1000
 - 0s - loss: 1.9534
Epoch 709/1000
 - 0s - loss: 1.9492
Epoch 710/1000
 - 0s - loss: 1.9449
Epoch 711/1000
 - 0s - loss: 1.9408
Epoch 712/1000
 - 0s - loss: 1.9369
Epoch 713/1000
 - 0s - loss: 1.9328
Epoch 714/1000
 - 0s - loss: 1.9286
Epoch 715/1000
 - 0s - loss:

Epoch 916/1000
 - 0s - loss: 1.2328
Epoch 917/1000
 - 0s - loss: 1.2300
Epoch 918/1000
 - 0s - loss: 1.2270
Epoch 919/1000
 - 0s - loss: 1.2239
Epoch 920/1000
 - 0s - loss: 1.2210
Epoch 921/1000
 - 0s - loss: 1.2182
Epoch 922/1000
 - 0s - loss: 1.2153
Epoch 923/1000
 - 0s - loss: 1.2125
Epoch 924/1000
 - 0s - loss: 1.2095
Epoch 925/1000
 - 0s - loss: 1.2065
Epoch 926/1000
 - 0s - loss: 1.2036
Epoch 927/1000
 - 0s - loss: 1.2008
Epoch 928/1000
 - 0s - loss: 1.1980
Epoch 929/1000
 - 0s - loss: 1.1950
Epoch 930/1000
 - 0s - loss: 1.1919
Epoch 931/1000
 - 0s - loss: 1.1889
Epoch 932/1000
 - 0s - loss: 1.1862
Epoch 933/1000
 - 0s - loss: 1.1834
Epoch 934/1000
 - 0s - loss: 1.1803
Epoch 935/1000
 - 0s - loss: 1.1771
Epoch 936/1000
 - 0s - loss: 1.1745
Epoch 937/1000
 - 0s - loss: 1.1717
Epoch 938/1000
 - 0s - loss: 1.1686
Epoch 939/1000
 - 0s - loss: 1.1655
Epoch 940/1000
 - 0s - loss: 1.1625
Epoch 941/1000
 - 0s - loss: 1.1597
Epoch 942/1000
 - 0s - loss: 1.1569
Epoch 943/1000
 - 0s - loss:

In [103]:
print(predict)

[[ 0.99941283  1.99881625  3.00129962  4.00021839  4.99874544  5.99876547
   6.99777317  7.44932175  7.20289135  6.55138731  5.87036705]]


In [109]:
test = np.array([11,10,9,8,7,6,5,4,3,2,1],dtype= float).reshape(1,1,11)
print(repr(test))
print(repr(model.predict(test)))

array([[[ 11.,  10.,   9.,   8.,   7.,   6.,   5.,   4.,   3.,   2.,   1.]]])
array([[ 0.27415532,  0.37451077,  1.644593  ,  2.06828904,  2.48848534,
         1.85010219,  2.53491879,  3.48078585,  2.80703664,  1.98639441,
         2.02631378]], dtype=float32)


In [111]:
test = np.array([1,2,3,4,5,6,7,8,0,0,0]).reshape(1,1,11)
print(repr(test))
print(repr(model.predict(test)))

array([[[1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0]]])
array([[ 0.85429066,  1.60297918,  2.48253107,  3.31893849,  3.96394587,
         4.40324497,  5.46658039,  6.06204414,  5.55680895,  4.89596224,
         4.50296974]], dtype=float32)


In [112]:
test = np.array([0,0,1,2,3,4,5,6,7,8,0]).reshape(1,1,11)
print(repr(test))
print(repr(model.predict(test)))

array([[[0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0]]])
array([[ 0.83437395,  1.67110944,  2.49239898,  3.26426053,  4.07995749,
         5.01898003,  5.92202663,  6.1503644 ,  6.03176117,  5.43200588,
         4.91055393]], dtype=float32)


In [80]:
print(repr(data))
print(repr(predict))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.]]])
array([[  0.9981935 ,   1.99906313,   2.99862719,   3.99979687,
          4.99885321,   6.00422001,   7.00098038,   8.00030899,
          9.000494  ,  10.00183487,  10.9978838 ]], dtype=float32)


In [73]:
print(repr(data))
print(repr(predict))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])
array([[  1.24809006e-03,  -4.94549051e-04,  -7.99059868e-04,
          5.47887757e-05,   5.50307799e-04,   6.50292262e-04,
         -4.24891710e-04,   4.40031290e-05,   1.99908030e+00,
          1.00021946e+00,  -3.95998359e-05]], dtype=float32)


In [129]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

# Input sequence
wholeSequence = [[0,0,0,0,0,0,0,0,0,2,1],
                 [0,0,0,0,0,0,0,0,2,1,0],
                 [0,0,0,0,0,0,0,2,1,0,0],
                 [0,0,0,0,0,0,2,1,0,0,0],
                 [0,0,0,0,0,2,1,0,0,0,0],
                 [0,0,0,0,2,1,0,0,0,0,0],
                 [0,0,0,2,1,0,0,0,0,0,0],
                 [0,0,2,1,0,0,0,0,0,0,0],
                 [0,2,1,0,0,0,0,0,0,0,0],
                 [2,1,0,0,0,0,0,0,0,0,0]]

# Preprocess Data:
wholeSequence = np.array(wholeSequence, dtype=float) # Convert to NP array.
data = wholeSequence[:-1] # all but last
target = wholeSequence[1:] # all but first

# Reshape training data for Keras LSTM model
# The training data needs to be (batchIndex, timeStepIndex, dimentionIndex)
# Single batch, 9 time steps, 11 dimentions
data = data.reshape((1, 9, 11))
target = target.reshape((1, 9, 11))
model = Sequential()  
model.add(LSTM(11, input_shape=(9, 11), unroll=False, return_sequences=True))
model.add(Dense(11))
model.compile(loss='mean_absolute_error', optimizer='adam')
model.fit(data, target, nb_epoch=1000, batch_size=1, verbose=2)

/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/keras/models.py:944: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/1000
 - 5s - loss: 0.3771
Epoch 2/1000
 - 0s - loss: 0.3739
Epoch 3/1000
 - 0s - loss: 0.3707
Epoch 4/1000
 - 0s - loss: 0.3676
Epoch 5/1000
 - 0s - loss: 0.3646
Epoch 6/1000
 - 0s - loss: 0.3616
Epoch 7/1000
 - 0s - loss: 0.3588
Epoch 8/1000
 - 0s - loss: 0.3562
Epoch 9/1000
 - 0s - loss: 0.3538
Epoch 10/1000
 - 0s - loss: 0.3515
Epoch 11/1000
 - 0s - loss: 0.3492
Epoch 12/1000
 - 0s - loss: 0.3470
Epoch 13/1000
 - 0s - loss: 0.3450
Epoch 14/1000
 - 0s - loss: 0.3433
Epoch 15/1000
 - 0s - loss: 0.3416
Epoch 16/1000
 - 0s - loss: 0.3400
Epoch 17/1000
 - 0s - loss: 0.3384
Epoch 18/1000
 - 0s - loss: 0.3369
Epoch 19/1000
 - 0s - loss: 0.3354
Epoch 20/1000
 - 0s - loss: 0.3340
Epoch 21/1000
 - 0s - loss: 0.3326
Epoch 22/1000
 - 0s - loss: 0.3312
Epoch 23/1000
 - 0s - loss: 0.3297
Epoch 24/1000
 - 0s - loss: 0.3284
Epoch 25/1000
 - 0s - loss: 0.3270
Epoch 26/1000
 - 0s - loss: 0.3257
Epoch 27/1000
 - 0s - loss: 0.3244
Epoch 28/1000
 - 0s - loss: 0.3232
Epoch 29/1000
 - 0s - loss: 0

Epoch 232/1000
 - 0s - loss: 0.2362
Epoch 233/1000
 - 0s - loss: 0.2358
Epoch 234/1000
 - 0s - loss: 0.2354
Epoch 235/1000
 - 0s - loss: 0.2350
Epoch 236/1000
 - 0s - loss: 0.2345
Epoch 237/1000
 - 0s - loss: 0.2341
Epoch 238/1000
 - 0s - loss: 0.2336
Epoch 239/1000
 - 0s - loss: 0.2332
Epoch 240/1000
 - 0s - loss: 0.2328
Epoch 241/1000
 - 0s - loss: 0.2323
Epoch 242/1000
 - 0s - loss: 0.2319
Epoch 243/1000
 - 0s - loss: 0.2314
Epoch 244/1000
 - 0s - loss: 0.2309
Epoch 245/1000
 - 0s - loss: 0.2305
Epoch 246/1000
 - 0s - loss: 0.2300
Epoch 247/1000
 - 0s - loss: 0.2296
Epoch 248/1000
 - 0s - loss: 0.2290
Epoch 249/1000
 - 0s - loss: 0.2286
Epoch 250/1000
 - 0s - loss: 0.2282
Epoch 251/1000
 - 0s - loss: 0.2276
Epoch 252/1000
 - 0s - loss: 0.2272
Epoch 253/1000
 - 0s - loss: 0.2267
Epoch 254/1000
 - 0s - loss: 0.2262
Epoch 255/1000
 - 0s - loss: 0.2257
Epoch 256/1000
 - 0s - loss: 0.2252
Epoch 257/1000
 - 0s - loss: 0.2247
Epoch 258/1000
 - 0s - loss: 0.2241
Epoch 259/1000
 - 0s - loss:

Epoch 460/1000
 - 0s - loss: 0.1127
Epoch 461/1000
 - 0s - loss: 0.1124
Epoch 462/1000
 - 0s - loss: 0.1123
Epoch 463/1000
 - 0s - loss: 0.1120
Epoch 464/1000
 - 0s - loss: 0.1119
Epoch 465/1000
 - 0s - loss: 0.1115
Epoch 466/1000
 - 0s - loss: 0.1112
Epoch 467/1000
 - 0s - loss: 0.1110
Epoch 468/1000
 - 0s - loss: 0.1107
Epoch 469/1000
 - 0s - loss: 0.1105
Epoch 470/1000
 - 0s - loss: 0.1101
Epoch 471/1000
 - 0s - loss: 0.1097
Epoch 472/1000
 - 0s - loss: 0.1095
Epoch 473/1000
 - 0s - loss: 0.1092
Epoch 474/1000
 - 0s - loss: 0.1090
Epoch 475/1000
 - 0s - loss: 0.1088
Epoch 476/1000
 - 0s - loss: 0.1086
Epoch 477/1000
 - 0s - loss: 0.1084
Epoch 478/1000
 - 0s - loss: 0.1082
Epoch 479/1000
 - 0s - loss: 0.1079
Epoch 480/1000
 - 0s - loss: 0.1077
Epoch 481/1000
 - 0s - loss: 0.1075
Epoch 482/1000
 - 0s - loss: 0.1072
Epoch 483/1000
 - 0s - loss: 0.1070
Epoch 484/1000
 - 0s - loss: 0.1068
Epoch 485/1000
 - 0s - loss: 0.1066
Epoch 486/1000
 - 0s - loss: 0.1063
Epoch 487/1000
 - 0s - loss:

Epoch 688/1000
 - 0s - loss: 0.0581
Epoch 689/1000
 - 0s - loss: 0.0581
Epoch 690/1000
 - 0s - loss: 0.0580
Epoch 691/1000
 - 0s - loss: 0.0577
Epoch 692/1000
 - 0s - loss: 0.0575
Epoch 693/1000
 - 0s - loss: 0.0578
Epoch 694/1000
 - 0s - loss: 0.0574
Epoch 695/1000
 - 0s - loss: 0.0575
Epoch 696/1000
 - 0s - loss: 0.0572
Epoch 697/1000
 - 0s - loss: 0.0570
Epoch 698/1000
 - 0s - loss: 0.0570
Epoch 699/1000
 - 0s - loss: 0.0569
Epoch 700/1000
 - 0s - loss: 0.0567
Epoch 701/1000
 - 0s - loss: 0.0567
Epoch 702/1000
 - 0s - loss: 0.0566
Epoch 703/1000
 - 0s - loss: 0.0564
Epoch 704/1000
 - 0s - loss: 0.0562
Epoch 705/1000
 - 0s - loss: 0.0560
Epoch 706/1000
 - 0s - loss: 0.0559
Epoch 707/1000
 - 0s - loss: 0.0557
Epoch 708/1000
 - 0s - loss: 0.0558
Epoch 709/1000
 - 0s - loss: 0.0557
Epoch 710/1000
 - 0s - loss: 0.0556
Epoch 711/1000
 - 0s - loss: 0.0554
Epoch 712/1000
 - 0s - loss: 0.0553
Epoch 713/1000
 - 0s - loss: 0.0552
Epoch 714/1000
 - 0s - loss: 0.0550
Epoch 715/1000
 - 0s - loss:

Epoch 916/1000
 - 0s - loss: 0.0357
Epoch 917/1000
 - 0s - loss: 0.0357
Epoch 918/1000
 - 0s - loss: 0.0358
Epoch 919/1000
 - 0s - loss: 0.0358
Epoch 920/1000
 - 0s - loss: 0.0357
Epoch 921/1000
 - 0s - loss: 0.0357
Epoch 922/1000
 - 0s - loss: 0.0357
Epoch 923/1000
 - 0s - loss: 0.0356
Epoch 924/1000
 - 0s - loss: 0.0355
Epoch 925/1000
 - 0s - loss: 0.0356
Epoch 926/1000
 - 0s - loss: 0.0355
Epoch 927/1000
 - 0s - loss: 0.0354
Epoch 928/1000
 - 0s - loss: 0.0354
Epoch 929/1000
 - 0s - loss: 0.0355
Epoch 930/1000
 - 0s - loss: 0.0355
Epoch 931/1000
 - 0s - loss: 0.0353
Epoch 932/1000
 - 0s - loss: 0.0355
Epoch 933/1000
 - 0s - loss: 0.0355
Epoch 934/1000
 - 0s - loss: 0.0355
Epoch 935/1000
 - 0s - loss: 0.0354
Epoch 936/1000
 - 0s - loss: 0.0354
Epoch 937/1000
 - 0s - loss: 0.0354
Epoch 938/1000
 - 0s - loss: 0.0353
Epoch 939/1000
 - 0s - loss: 0.0354
Epoch 940/1000
 - 0s - loss: 0.0353
Epoch 941/1000
 - 0s - loss: 0.0353
Epoch 942/1000
 - 0s - loss: 0.0353
Epoch 943/1000
 - 0s - loss:

In [117]:

print(model.predict())

[[[ -1.87188387e-04   3.17558646e-04   9.70387831e-04  -4.90754843e-04
     4.02197242e-04   2.26404518e-04  -1.60082709e-06  -5.04188240e-04
     2.00027776e+00   1.00061905e+00   5.11780381e-05]
  [ -9.15020704e-04   2.13983655e-03   1.30700506e-03  -3.31759453e-04
     3.32251191e-04   7.12860376e-04  -1.45161792e-03   1.99851131e+00
     9.98682976e-01   2.25245953e-04  -1.26659870e-06]
  [  4.17098403e-04   1.64888799e-03   1.32031180e-03   1.24314427e-03
     5.84572554e-05   2.23491713e-03   1.99704599e+00   9.98701155e-01
    -6.25580549e-04   1.69709325e-04  -4.00759280e-04]
  [ -1.25974417e-04   1.79134309e-03   5.82421198e-04  -9.15825367e-04
     1.64644420e-03   2.00076675e+00   9.98802304e-01   1.41208619e-03
    -3.92884016e-04   4.04745340e-04  -9.10460949e-06]
  [  4.90635633e-04  -8.98137689e-04   3.57870013e-05  -2.07960606e-04
     2.00074577e+00   1.00130737e+00  -4.53437679e-07   1.02152675e-03
     1.38506293e-03   4.76017594e-04   2.98216939e-04]
  [ -4.57763672