In [7]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

# Input sequence
wholeSequence = [[0,0,0,0,0,0,0,0,0,2,1],
                 [0,0,0,0,0,0,0,0,2,1,0],
                 [0,0,0,0,0,0,0,2,1,0,0],
                 [0,0,0,0,0,0,2,1,0,0,0],
                 [0,0,0,0,0,2,1,0,0,0,0],
                 [0,0,0,0,2,1,0,0,0,0,0],
                 [0,0,0,2,1,0,0,0,0,0,0],
                 [0,0,2,1,0,0,0,0,0,0,0],
                 [0,2,1,0,0,0,0,0,0,0,0],
                 [2,1,0,0,0,0,0,0,0,0,0]]

# Preprocess Data: (This does not work)
wholeSequence = np.array(wholeSequence, dtype=float) # Convert to NP array.
data = wholeSequence[:] # all but last
target = wholeSequence[-1] # all but first

# This does not work:
# Reshape training data for Keras LSTM model
# The training data needs to be (batchIndex, timeStepIndex, dimentionIndex)
data = data.reshape((1, 10, 11)) # Single batch, 9 time steps, 11 dimentions
target = target.reshape((-1, 11)) # Corresponds to shape (None, 11)

# Build Model
model = Sequential()  
model.add(LSTM(11, input_shape=(10, 11), unroll=False))
model.add(Dense(11))
model.compile(loss='mean_absolute_error', optimizer='adam')
model.fit(data, target, nb_epoch=1000, batch_size=1, verbose=2)

# Do the output values match the target values?
predict = model.predict(data)
print(repr(data))
print(repr(predict))

/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/keras/models.py:944: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/1000
 - 1s - loss: 0.3601
Epoch 2/1000
 - 0s - loss: 0.3539
Epoch 3/1000
 - 0s - loss: 0.3479
Epoch 4/1000
 - 0s - loss: 0.3438
Epoch 5/1000
 - 0s - loss: 0.3413
Epoch 6/1000
 - 0s - loss: 0.3383
Epoch 7/1000
 - 0s - loss: 0.3349
Epoch 8/1000
 - 0s - loss: 0.3312
Epoch 9/1000
 - 0s - loss: 0.3278
Epoch 10/1000
 - 0s - loss: 0.3245
Epoch 11/1000
 - 0s - loss: 0.3216
Epoch 12/1000
 - 0s - loss: 0.3193
Epoch 13/1000
 - 0s - loss: 0.3172
Epoch 14/1000
 - 0s - loss: 0.3157
Epoch 15/1000
 - 0s - loss: 0.3135
Epoch 16/1000
 - 0s - loss: 0.3112
Epoch 17/1000
 - 0s - loss: 0.3092
Epoch 18/1000
 - 0s - loss: 0.3070
Epoch 19/1000
 - 0s - loss: 0.3045
Epoch 20/1000
 - 0s - loss: 0.3016
Epoch 21/1000
 - 0s - loss: 0.3000
Epoch 22/1000
 - 0s - loss: 0.2983
Epoch 23/1000
 - 0s - loss: 0.2961
Epoch 24/1000
 - 0s - loss: 0.2946
Epoch 25/1000
 - 0s - loss: 0.2930
Epoch 26/1000
 - 0s - loss: 0.2915
Epoch 27/1000
 - 0s - loss: 0.2899
Epoch 28/1000
 - 0s - loss: 0.2881
Epoch 29/1000
 - 0s - loss: 0

 - 0s - loss: 0.0023
Epoch 232/1000
 - 0s - loss: 0.0020
Epoch 233/1000
 - 0s - loss: 0.0020
Epoch 234/1000
 - 0s - loss: 0.0025
Epoch 235/1000
 - 0s - loss: 0.0028
Epoch 236/1000
 - 0s - loss: 0.0029
Epoch 237/1000
 - 0s - loss: 0.0018
Epoch 238/1000
 - 0s - loss: 0.0013
Epoch 239/1000
 - 0s - loss: 0.0021
Epoch 240/1000
 - 0s - loss: 0.0031
Epoch 241/1000
 - 0s - loss: 0.0027
Epoch 242/1000
 - 0s - loss: 0.0018
Epoch 243/1000
 - 0s - loss: 0.0013
Epoch 244/1000
 - 0s - loss: 0.0024
Epoch 245/1000
 - 0s - loss: 0.0027
Epoch 246/1000
 - 0s - loss: 0.0024
Epoch 247/1000
 - 0s - loss: 0.0019
Epoch 248/1000
 - 0s - loss: 0.0022
Epoch 249/1000
 - 0s - loss: 0.0022
Epoch 250/1000
 - 0s - loss: 0.0018
Epoch 251/1000
 - 0s - loss: 0.0015
Epoch 252/1000
 - 0s - loss: 0.0024
Epoch 253/1000
 - 0s - loss: 0.0024
Epoch 254/1000
 - 0s - loss: 0.0013
Epoch 255/1000
 - 0s - loss: 0.0011
Epoch 256/1000
 - 0s - loss: 0.0019
Epoch 257/1000
 - 0s - loss: 0.0020
Epoch 258/1000
 - 0s - loss: 0.0019
Epoch 2

Epoch 459/1000
 - 0s - loss: 0.0013
Epoch 460/1000
 - 0s - loss: 0.0015
Epoch 461/1000
 - 0s - loss: 0.0022
Epoch 462/1000
 - 0s - loss: 0.0021
Epoch 463/1000
 - 0s - loss: 0.0013
Epoch 464/1000
 - 0s - loss: 0.0014
Epoch 465/1000
 - 0s - loss: 0.0016
Epoch 466/1000
 - 0s - loss: 0.0012
Epoch 467/1000
 - 0s - loss: 0.0013
Epoch 468/1000
 - 0s - loss: 0.0015
Epoch 469/1000
 - 0s - loss: 0.0013
Epoch 470/1000
 - 0s - loss: 8.2557e-04
Epoch 471/1000
 - 0s - loss: 8.0417e-04
Epoch 472/1000
 - 0s - loss: 0.0011
Epoch 473/1000
 - 0s - loss: 0.0014
Epoch 474/1000
 - 0s - loss: 0.0011
Epoch 475/1000
 - 0s - loss: 0.0011
Epoch 476/1000
 - 0s - loss: 0.0013
Epoch 477/1000
 - 0s - loss: 0.0016
Epoch 478/1000
 - 0s - loss: 0.0014
Epoch 479/1000
 - 0s - loss: 9.3367e-04
Epoch 480/1000
 - 0s - loss: 0.0013
Epoch 481/1000
 - 0s - loss: 0.0017
Epoch 482/1000
 - 0s - loss: 0.0021
Epoch 483/1000
 - 0s - loss: 0.0019
Epoch 484/1000
 - 0s - loss: 0.0018
Epoch 485/1000
 - 0s - loss: 0.0010
Epoch 486/1000
 

Epoch 684/1000
 - 0s - loss: 0.0012
Epoch 685/1000
 - 0s - loss: 0.0012
Epoch 686/1000
 - 0s - loss: 0.0016
Epoch 687/1000
 - 0s - loss: 0.0018
Epoch 688/1000
 - 0s - loss: 0.0017
Epoch 689/1000
 - 0s - loss: 0.0018
Epoch 690/1000
 - 0s - loss: 0.0013
Epoch 691/1000
 - 0s - loss: 0.0015
Epoch 692/1000
 - 0s - loss: 0.0020
Epoch 693/1000
 - 0s - loss: 0.0021
Epoch 694/1000
 - 0s - loss: 0.0017
Epoch 695/1000
 - 0s - loss: 0.0015
Epoch 696/1000
 - 0s - loss: 0.0015
Epoch 697/1000
 - 0s - loss: 0.0017
Epoch 698/1000
 - 0s - loss: 0.0018
Epoch 699/1000
 - 0s - loss: 0.0015
Epoch 700/1000
 - 0s - loss: 0.0017
Epoch 701/1000
 - 0s - loss: 0.0017
Epoch 702/1000
 - 0s - loss: 0.0015
Epoch 703/1000
 - 0s - loss: 0.0015
Epoch 704/1000
 - 0s - loss: 0.0018
Epoch 705/1000
 - 0s - loss: 0.0019
Epoch 706/1000
 - 0s - loss: 0.0016
Epoch 707/1000
 - 0s - loss: 0.0011
Epoch 708/1000
 - 0s - loss: 0.0014
Epoch 709/1000
 - 0s - loss: 0.0021
Epoch 710/1000
 - 0s - loss: 0.0020
Epoch 711/1000
 - 0s - loss:

Epoch 908/1000
 - 0s - loss: 0.0014
Epoch 909/1000
 - 0s - loss: 0.0013
Epoch 910/1000
 - 0s - loss: 7.3247e-04
Epoch 911/1000
 - 0s - loss: 0.0010
Epoch 912/1000
 - 0s - loss: 0.0013
Epoch 913/1000
 - 0s - loss: 0.0011
Epoch 914/1000
 - 0s - loss: 0.0012
Epoch 915/1000
 - 0s - loss: 0.0013
Epoch 916/1000
 - 0s - loss: 8.7871e-04
Epoch 917/1000
 - 0s - loss: 0.0013
Epoch 918/1000
 - 0s - loss: 0.0013
Epoch 919/1000
 - 0s - loss: 0.0015
Epoch 920/1000
 - 0s - loss: 0.0016
Epoch 921/1000
 - 0s - loss: 0.0017
Epoch 922/1000
 - 0s - loss: 0.0013
Epoch 923/1000
 - 0s - loss: 0.0012
Epoch 924/1000
 - 0s - loss: 0.0013
Epoch 925/1000
 - 0s - loss: 0.0019
Epoch 926/1000
 - 0s - loss: 0.0021
Epoch 927/1000
 - 0s - loss: 0.0015
Epoch 928/1000
 - 0s - loss: 5.7378e-04
Epoch 929/1000
 - 0s - loss: 0.0013
Epoch 930/1000
 - 0s - loss: 0.0017
Epoch 931/1000
 - 0s - loss: 0.0017
Epoch 932/1000
 - 0s - loss: 0.0016
Epoch 933/1000
 - 0s - loss: 0.0017
Epoch 934/1000
 - 0s - loss: 0.0012
Epoch 935/1000
 

In [8]:
#unroll false
print(repr(data))
print(repr(predict))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])
array([[  2.00119090e+00,   1.00113189e+00,  -6.76235184e-04,
         -9.20556486e-05,  -1.11499429e-03,   2.27801502e-05,
         -1.57510862e-04,  -1.81961060e-03,  -1.88708678e-03,
          1.39614940e-03,   2.30371952e-05]], dtype=float32)


In [6]:
#unroll = true
print(repr(data))
print(repr(predict))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])
array([[  2.00163889e+00,   1.00488424e+00,  -1.28257181e-03,
          4.54582274e-04,   2.54215300e-03,   1.09260529e-03,
         -1.34858117e-03,  -3.08340974e-03,   5.00489026e-04,
         -1.51191093e-03,   1.50643289e-03]], dtype=float32)


In [ ]:
1,0 0 0 0 0 